/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.sprinkle.views;
import com.sprinkle.models.CategoryModel;
import com.sprinkle.controllers.CategoryController;

import javax.swing.*;
import java.awt.*;
/**
 *
 * @author User
 */
public class AddCategoryForm extends javax.swing.JDialog {
    private CategoryController categoryController = new CategoryController();

    /**
     * Creates new form AddDialogForm
     */
    public AddCategoryForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
//        initComponents();
          initCustomForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initCustomForm() {
           setTitle("Add New Category");

           JLabel labelName = new JLabel("Category Name:");
           JTextField textName = new JTextField(20);

           JButton btnSave = new JButton("Save");
           JButton btnCancel = new JButton("Cancel");

           JPanel panel = new JPanel(new GridBagLayout());
           GridBagConstraints gbc = new GridBagConstraints();
           gbc.insets = new Insets(5, 5, 5, 5);
           gbc.anchor = GridBagConstraints.WEST;

           int row = 0;
           gbc.gridx = 0; gbc.gridy = row; panel.add(labelName, gbc);
           gbc.gridx = 1; panel.add(textName, gbc);

           gbc.gridy = ++row; gbc.gridx = 0; panel.add(btnSave, gbc);
           gbc.gridx = 1; panel.add(btnCancel, gbc);

           getContentPane().removeAll();
           getContentPane().add(panel);
           revalidate();
           repaint();
           pack();
           setLocationRelativeTo(null);

           // Tombol aksi
           btnCancel.addActionListener(e -> dispose());

           btnSave.addActionListener(e -> {
               String name = textName.getText().trim();
               if (name.isEmpty()) {
                   JOptionPane.showMessageDialog(this, "Category name cannot be empty.");
                   return;
               }

               CategoryModel newCategory = new CategoryModel(0, name); // id = 0, diasumsikan auto increment
               boolean success = categoryController.addCategory(newCategory); // method harus ada di controller & DAO

               if (success) {
                   JOptionPane.showMessageDialog(this, "Category added successfully.");
                   dispose();
               } else {
                   JOptionPane.showMessageDialog(this, "Failed to add category.");
               }
           });
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            AddCategoryForm dialog = new AddCategoryForm(null, true);
               dialog.setVisible(true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
