/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.sprinkle.views;
import com.sprinkle.controllers.MemberController;
import com.sprinkle.models.MemberModel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.sql.Date;
/**
 *
 * @author User
 */
public class EditMemberForm extends javax.swing.JDialog {
private MemberModel member;
private MemberController memberController = new MemberController();


    /**
     * Creates new form AddBookForm
     */
    public EditMemberForm(java.awt.Frame parent, boolean modal, MemberModel member) {
        super(parent, modal);
        this.member = member;
        initCustomForm();
    }
    
    private void initCustomForm() {
        setTitle("Edit Member");

        JLabel labelName = new JLabel("Name:");
        JTextField textName = new JTextField(member.getName(), 30);

        JLabel labelUsername = new JLabel("Username:");
        JTextField textUsername = new JTextField(member.getUsername(), 30);

        JLabel labelPhone = new JLabel("Phone:");
        JTextField textPhone = new JTextField(member.getPhone(), 20);

        JLabel labelEmail = new JLabel("Email:");
        JTextField textEmail = new JTextField(member.getEmail(), 30);

        JLabel labelAddress = new JLabel("Address:");
        JTextField textAddress = new JTextField(member.getAddress(), 50);

        JLabel labelDate = new JLabel("Registered At:");
        JTextField textDate = new JTextField(new SimpleDateFormat("yyyy-MM-dd").format(member.getRegistrationDate()));
        textDate.setEditable(false); // Biasanya tanggal pendaftaran tidak bisa diedit

        JButton btnSave = new JButton("Save");
        JButton btnCancel = new JButton("Cancel");

        JPanel panel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.anchor = GridBagConstraints.WEST;

        int row = 0;
        gbc.gridx = 0; gbc.gridy = row; panel.add(labelName, gbc);
        gbc.gridx = 1; panel.add(textName, gbc);

        gbc.gridy = ++row; gbc.gridx = 0; panel.add(labelUsername, gbc);
        gbc.gridx = 1; panel.add(textUsername, gbc);

        gbc.gridy = ++row; gbc.gridx = 0; panel.add(labelPhone, gbc);
        gbc.gridx = 1; panel.add(textPhone, gbc);

        gbc.gridy = ++row; gbc.gridx = 0; panel.add(labelEmail, gbc);
        gbc.gridx = 1; panel.add(textEmail, gbc);

        gbc.gridy = ++row; gbc.gridx = 0; panel.add(labelAddress, gbc);
        gbc.gridx = 1; panel.add(textAddress, gbc);

        gbc.gridy = ++row; gbc.gridx = 0; panel.add(labelDate, gbc);
        gbc.gridx = 1; panel.add(textDate, gbc);

        gbc.gridy = ++row; gbc.gridx = 0; panel.add(btnSave, gbc);
        gbc.gridx = 1; panel.add(btnCancel, gbc);

        getContentPane().removeAll();
        getContentPane().add(panel);
        revalidate();
        repaint();
        pack();
        setLocationRelativeTo(null);

        btnCancel.addActionListener(e -> dispose());
        btnSave.addActionListener(e -> {
            try {
                String name = textName.getText();
                String username = textUsername.getText();
                String phone = textPhone.getText();
                String email = textEmail.getText();
                String address = textAddress.getText();

                if (name.isEmpty() || username.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Name and Username cannot be empty.");
                    return;
                }

                member.setName(name);
                member.setUsername(username);
                member.setPhone(phone);
                member.setEmail(email);
                member.setAddress(address);

                boolean success = memberController.updateMember(member); // pastikan method ini ada

                if (success) {
                    JOptionPane.showMessageDialog(this, "Member updated successfully.");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to update member.");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                ex.printStackTrace();
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Buat dummy book atau ambil dari database sesuai kebutuhan
            // Dummy member
            MemberModel dummyMember = new MemberModel(
                1,                             // memberId
                "john_doe",                   // username
                "John Doe",                   // name
                "john@example.com",          // email
                "081234567890",              // phone
                "Jl. Merdeka No. 1",         // address
                new Date(System.currentTimeMillis()) // registrationDate (hari ini)
            );

            EditMemberForm dialog = new EditMemberForm(new javax.swing.JFrame(), true, dummyMember);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
